<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" encoding="UTF-8">

	<!-- DO NOT CHANGE ANYTHING BETWEEN THESE (unless you know 100% what you are changing)-->
	<!-- Further info: This defines critical project details, like the .net version, C# language version, null enable and do not generate assembly info (we need a custom one) -->
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<LangVersion>Latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<!-- Debug is useless for a mod -->
		<DebugType>none</DebugType>
	</PropertyGroup>
	<!-- DO NOT CHANGE ANYTHING BETWEEN THESE -->

	<PropertyGroup>
		<!-- This should point to wherever your games primary EXE is -->
		<TheLongDarkPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark</TheLongDarkPath>
		<Mods>$(TheLongDarkPath)\Mods</Mods>
		<Plugins>$(TheLongDarkPath)\Plugins</Plugins>
		<UserData>$(TheLongDarkPath)\UserData</UserData>
		<UserLibs>$(TheLongDarkPath)\UserLibs</UserLibs>
		<!-- These paths are for various mod resources -->
		<ModResources>P:\Modding\The Long Dark</ModResources>
		<UPDATES>$(ModResources)\UPDATES</UPDATES>
		<MyMods>$(ModResources)\MyMods</MyMods>
		<Libraries>$(ModResources)\Libraries</Libraries>
		<!--The path to this mod-->
		<This>$(MyMods)\MapManager</This>

		<!--Path to a release folder-->
		<ReleaseFolderPath>$(This)\Release</ReleaseFolderPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="0Harmony">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\MelonLoader\0Harmony.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\MelonLoader\Managed\Assembly-CSharp.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Il2Cppmscorlib">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\MelonLoader\Managed\Il2Cppmscorlib.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Il2CppSystem">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\MelonLoader\Managed\Il2CppSystem.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Il2CppSystem.Core">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\MelonLoader\Managed\Il2CppSystem.Core.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="MelonLoader">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\MelonLoader\MelonLoader.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnhollowerBaseLib">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\MelonLoader\Managed\UnhollowerBaseLib.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="ModSettings">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\Mods\ModSettings.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="KeyboardUtilities">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\Mods\KeyboardUtilities.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\MelonLoader\Managed\UnityEngine.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\MelonLoader\Managed\UnityEngine.CoreModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\MelonLoader\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\MelonLoader\Managed\UnityEngine.UI.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.AssetBundleModule">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\MelonLoader\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>
	

	<!-- Most commonly used using's. Add to this so you dont need to define them in the cs files -->
	<ItemGroup>
		<Using Include="System.Reflection" />
		<Using Include="HarmonyLib" />
		<Using Include="MelonLoader" />
		<Using Include="UnityEngine" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Utilities\" />
	</ItemGroup>

	<!-- This is a build event. It will copy your dll to the currently defined TheLongDarkPath's Mods folder -->
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<!-- This copies the mods files to the games mod dir -->
		<Copy Condition="Exists('$(Mods)')" SourceFiles="$(TargetPath)" DestinationFolder="$(Mods)" />
		<!-- This copies the mods files to a designated release folder. Speeds up finding the dll after a build -->
		<Copy Condition="Exists('$(ReleaseFolderPath)')" SourceFiles="$(TargetPath)" DestinationFolder="$(ReleaseFolderPath)" />
	</Target>


</Project>
